# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Stat 386 Data Science Blog 
email: fongspe28@gmail.com 
description: "I will make at least one blog post about data science for my class"
baseurl: "/stat386-blog-theme" # the name of the repository 
url: "https://fong31h.github.io" #  change this to "https://<your-github-username>.github.io"
image: https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.si.com%2Fmlb%2F2023%2F08%2F18%2Fgiants-logan-webb-workhorse-innings-leader-mlb&psig=AOvVaw0N_FGFPEC-v3QF8Xz0Qm_5&ust=1695922849256000&source=images&cd=vfe&opi=89978449&ved=0CA8QjRxqFwoTCIjrkYqry4EDFQAAAAAdAAAAABAE
author: Spencer Fong
copyright: SF # Your initials or what you want the copyright to be.  Leave empty for no copyright
footer_description: 'The above image is of Logan Webb, starting pitcher and ace for the San Francisco Giants of Major League Baseball'


# Social media users names.  Leave fields blank that you don't want displayed
twitter_username:
github_username:
linkedin_username:
dribbble_username: 
facebook_username:
flickr_username:
instagram_username: 
pinterest_username:
youtube_username: 
googleplus_username:

plugins:
  - jekyll-feed

